"""add_teaching_assistant_models

Revision ID: 2096e83ae875
Revises: 4ebe485a33df
Create Date: 2026-02-11 00:53:37.765644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2096e83ae875'
down_revision = '4ebe485a33df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_course_modules_course_id', 'course_modules', ['course_id'], unique=False)
    op.create_index('idx_course_modules_course_order', 'course_modules', ['course_id', 'order_index'], unique=False)
    op.create_index('idx_course_modules_course_order_unique', 'course_modules', ['course_id', 'order_index'], unique=True)
    op.create_index('idx_course_modules_created_at', 'course_modules', ['created_at'], unique=False)
    op.create_index('idx_course_modules_name', 'course_modules', ['name'], unique=False)
    op.create_index('idx_course_modules_order_index', 'course_modules', ['order_index'], unique=False)
    op.create_index('idx_course_modules_tenant_course', 'course_modules', ['tenant_id', 'course_id'], unique=False)
    op.create_index('idx_course_modules_tenant_created', 'course_modules', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_course_modules_tenant_id', 'course_modules', ['tenant_id'], unique=False)
    op.create_table('student_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key identifier for the student interaction'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Foreign key reference to tenants table for multi-tenancy support'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='UUID identifier of the student who initiated the interaction'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='UUID identifier of the course context for this interaction'),
    sa.Column('module_id', sa.UUID(), nullable=True, comment='UUID identifier of the specific module within the course'),
    sa.Column('query', sa.Text(), nullable=False, comment='The original question or prompt submitted by the student'),
    sa.Column('answer', sa.Text(), nullable=False, comment='The response provided by the Teaching Assistant AI'),
    sa.Column('topic', sa.String(length=255), nullable=True, comment='The identified topic or subject area for this interaction'),
    sa.Column('mode', sa.Enum('TEXT', 'VOICE', 'MIXED', name='interaction_mode_enum'), nullable=False, comment='Mode of interaction: text, voice, or mixed input/output'),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment="URL to the audio recording of the student's question (for voice interactions)"),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True, comment='Duration of the audio recording in seconds'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='RAG context data including retrieved documents and metadata stored as JSONB'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of source documents and references used for generating the answer'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='AI confidence score for the generated answer (0.0 to 1.0)'),
    sa.Column('feedback', sa.Integer(), nullable=True, comment='Student feedback rating for the answer quality (1 to 5 stars)'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='Optional written feedback comment from the student'),
    sa.Column('escalated_to_mentor', sa.Boolean(), nullable=False, comment='Flag indicating if this interaction was escalated to a human mentor'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when the interaction was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the interaction was last updated'),
    sa.CheckConstraint('audio_duration_seconds >= 0', name='chk_audio_duration_positive'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='chk_confidence_range'),
    sa.CheckConstraint('feedback >= 1 AND feedback <= 5', name='chk_feedback_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_interactions_confidence_created', 'student_interactions', ['confidence', 'created_at'], unique=False)
    op.create_index('idx_student_interactions_course_module', 'student_interactions', ['course_id', 'module_id'], unique=False)
    op.create_index('idx_student_interactions_escalated_created', 'student_interactions', ['escalated_to_mentor', 'created_at'], unique=False)
    op.create_index('idx_student_interactions_mode_audio', 'student_interactions', ['mode', 'audio_url'], unique=False)
    op.create_index('idx_student_interactions_module_topic', 'student_interactions', ['module_id', 'topic'], unique=False)
    op.create_index('idx_student_interactions_student_course', 'student_interactions', ['student_id', 'course_id'], unique=False)
    op.create_index('idx_student_interactions_student_created', 'student_interactions', ['student_id', 'created_at'], unique=False)
    op.create_index('idx_student_interactions_tenant_course', 'student_interactions', ['tenant_id', 'course_id'], unique=False)
    op.create_index('idx_student_interactions_tenant_created', 'student_interactions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_student_interactions_tenant_student', 'student_interactions', ['tenant_id', 'student_id'], unique=False)
    op.create_table('student_nudges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('nudge_type', sa.Enum('INACTIVITY_REMINDER', 'CONFUSION_HELP', 'RISK_ALERT', 'ENCOURAGEMENT', name='nudgetype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'VOICE', name='channel'), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='nudgestatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_nudges_channel_status', 'student_nudges', ['channel', 'status'], unique=False)
    op.create_index('idx_student_nudges_nudge_type', 'student_nudges', ['nudge_type'], unique=False)
    op.create_index('idx_student_nudges_read_at', 'student_nudges', ['read_at'], unique=False)
    op.create_index('idx_student_nudges_sent_at', 'student_nudges', ['sent_at'], unique=False)
    op.create_index('idx_student_nudges_status_priority', 'student_nudges', ['status', 'priority'], unique=False)
    op.create_index('idx_student_nudges_student_type', 'student_nudges', ['student_id', 'nudge_type'], unique=False)
    op.create_index('idx_student_nudges_tenant_created', 'student_nudges', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_student_nudges_tenant_student', 'student_nudges', ['tenant_id', 'student_id'], unique=False)
    op.create_table('voice_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voice_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('session_id', name='uq_voice_conv_session_id')
    )
    op.create_index('idx_voice_conv_course_status', 'voice_conversations', ['course_id', 'status'], unique=False)
    op.create_index('idx_voice_conv_session_id', 'voice_conversations', ['session_id'], unique=False)
    op.create_index('idx_voice_conv_started_at', 'voice_conversations', ['started_at'], unique=False)
    op.create_index('idx_voice_conv_status', 'voice_conversations', ['status'], unique=False)
    op.create_index('idx_voice_conv_student_started', 'voice_conversations', ['student_id', 'started_at'], unique=False)
    op.create_index('idx_voice_conv_tenant_course', 'voice_conversations', ['tenant_id', 'course_id'], unique=False)
    op.create_index('idx_voice_conv_tenant_id', 'voice_conversations', ['tenant_id'], unique=False)
    op.create_index('idx_voice_conv_tenant_student', 'voice_conversations', ['tenant_id', 'student_id'], unique=False)
    op.alter_column('demos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_voice_conv_tenant_student', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_tenant_id', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_tenant_course', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_student_started', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_status', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_started_at', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_session_id', table_name='voice_conversations')
    op.drop_index('idx_voice_conv_course_status', table_name='voice_conversations')
    op.drop_table('voice_conversations')
    op.drop_index('idx_student_nudges_tenant_student', table_name='student_nudges')
    op.drop_index('idx_student_nudges_tenant_created', table_name='student_nudges')
    op.drop_index('idx_student_nudges_student_type', table_name='student_nudges')
    op.drop_index('idx_student_nudges_status_priority', table_name='student_nudges')
    op.drop_index('idx_student_nudges_sent_at', table_name='student_nudges')
    op.drop_index('idx_student_nudges_read_at', table_name='student_nudges')
    op.drop_index('idx_student_nudges_nudge_type', table_name='student_nudges')
    op.drop_index('idx_student_nudges_channel_status', table_name='student_nudges')
    op.drop_table('student_nudges')
    op.drop_index('idx_student_interactions_tenant_student', table_name='student_interactions')
    op.drop_index('idx_student_interactions_tenant_created', table_name='student_interactions')
    op.drop_index('idx_student_interactions_tenant_course', table_name='student_interactions')
    op.drop_index('idx_student_interactions_student_created', table_name='student_interactions')
    op.drop_index('idx_student_interactions_student_course', table_name='student_interactions')
    op.drop_index('idx_student_interactions_module_topic', table_name='student_interactions')
    op.drop_index('idx_student_interactions_mode_audio', table_name='student_interactions')
    op.drop_index('idx_student_interactions_escalated_created', table_name='student_interactions')
    op.drop_index('idx_student_interactions_course_module', table_name='student_interactions')
    op.drop_index('idx_student_interactions_confidence_created', table_name='student_interactions')
    op.drop_table('student_interactions')
    op.drop_index('idx_course_modules_tenant_id', table_name='course_modules')
    op.drop_index('idx_course_modules_tenant_created', table_name='course_modules')
    op.drop_index('idx_course_modules_tenant_course', table_name='course_modules')
    op.drop_index('idx_course_modules_order_index', table_name='course_modules')
    op.drop_index('idx_course_modules_name', table_name='course_modules')
    op.drop_index('idx_course_modules_created_at', table_name='course_modules')
    op.drop_index('idx_course_modules_course_order_unique', table_name='course_modules')
    op.drop_index('idx_course_modules_course_order', table_name='course_modules')
    op.drop_index('idx_course_modules_course_id', table_name='course_modules')
    op.drop_table('course_modules')
    # ### end Alembic commands ###
