"""initial tables

Revision ID: 2b186ef4ecbf
Revises: 
Create Date: 2026-02-06 02:16:50.292111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b186ef4ecbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_plan', sa.Enum('STARTER', 'GROWTH', 'ENTERPRISE', 'ADMIN', name='subscriptionplan'), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_plan_credits', 'tenants', ['subscription_plan', 'credits_remaining'], unique=False)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_subscription_plan'), 'tenants', ['subscription_plan'], unique=False)
    op.create_table('analytics_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTRATION', 'LEAD_CREATED', 'LEAD_UPDATED', 'LEAD_CONVERTED', 'LEAD_QUALIFIED', 'CHATBOT_SESSION_START', 'CHATBOT_SESSION_END', 'CHATBOT_INTENT_DETECTED', 'CHATBOT_ESCALATION', 'CALL_INITIATED', 'CALL_COMPLETED', 'EMAIL_SENT', 'SMS_SENT', 'DEMO_SCHEDULED', 'DEMO_ATTENDED', 'DEMO_NO_SHOW', 'DEMO_RESCHEDULED', 'COURSE_ENROLLED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'STUDENT_LOGIN', 'MODULE_COMPLETED', 'ASSIGNMENT_SUBMITTED', 'QUIZ_COMPLETED', 'QUESTION_ASKED', 'ANSWER_PROVIDED', 'CONCEPT_EXPLAINED', 'API_REQUEST', 'ERROR_OCCURRED', 'RATE_LIMIT_HIT', 'REVENUE_GENERATED', 'REFUND_PROCESSED', 'SUBSCRIPTION_UPGRADED', 'SUBSCRIPTION_DOWNGRADED', name='eventtype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.String(length=20), nullable=True),
    sa.Column('response_time_ms', sa.String(length=20), nullable=True),
    sa.Column('revenue_amount', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('stack_trace', sa.String(length=5000), nullable=True),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('variant_id', sa.String(length=100), nullable=True),
    sa.Column('is_test_data', sa.String(length=10), nullable=True),
    sa.Column('data_quality_score', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_campaign', 'analytics_events', ['campaign_id', 'utm_source'], unique=False)
    op.create_index('idx_analytics_created_at', 'analytics_events', ['created_at'], unique=False)
    op.create_index('idx_analytics_entity', 'analytics_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_analytics_errors', 'analytics_events', ['error_code', 'created_at'], unique=False)
    op.create_index('idx_analytics_revenue', 'analytics_events', ['revenue_amount', 'currency'], unique=False)
    op.create_index('idx_analytics_session', 'analytics_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_analytics_source_channel', 'analytics_events', ['source', 'channel'], unique=False)
    op.create_index('idx_analytics_tenant_event_type', 'analytics_events', ['tenant_id', 'event_type'], unique=False)
    op.create_index('idx_analytics_test_data', 'analytics_events', ['is_test_data'], unique=False)
    op.create_index('idx_analytics_user', 'analytics_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_entity_id'), 'analytics_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_entity_type'), 'analytics_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_is_test_data'), 'analytics_events', ['is_test_data'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_source'), 'analytics_events', ['source'], unique=False)
    op.create_index(op.f('ix_analytics_events_tenant_id'), 'analytics_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('syllabus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('indexed', sa.String(length=10), nullable=True),
    sa.Column('content_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('is_published', sa.String(length=10), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_course_category_published', 'courses', ['category', 'is_published'], unique=False)
    op.create_index('idx_course_enrollment_count', 'courses', ['enrollment_count'], unique=False)
    op.create_index('idx_course_indexed', 'courses', ['indexed'], unique=False)
    op.create_index('idx_course_tenant_active', 'courses', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_indexed'), 'courses', ['indexed'], unique=False)
    op.create_index(op.f('ix_courses_is_active'), 'courses', ['is_active'], unique=False)
    op.create_index(op.f('ix_courses_is_published'), 'courses', ['is_published'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MENTOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tenant_email', 'users', ['tenant_id', 'email'], unique=False)
    op.create_index('idx_user_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('WEBSITE', 'CHATBOT', 'REFERRAL', 'SOCIAL_MEDIA', 'ADVERTISING', 'EMAIL_CAMPAIGN', 'DIRECT', 'OTHER', name='leadsource'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'DEMO_SCHEDULED', 'DEMO_COMPLETED', 'ENROLLED', 'LOST', 'NURTURING', name='leadstatus'), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('interested_courses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgencylevel'), nullable=False),
    sa.Column('chatbot_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('conversion_probability', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_assigned_status', 'leads', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_lead_email_phone', 'leads', ['email', 'phone'], unique=False)
    op.create_index('idx_lead_engagement_score', 'leads', ['engagement_score'], unique=False)
    op.create_index('idx_lead_tenant_source', 'leads', ['tenant_id', 'source'], unique=False)
    op.create_index('idx_lead_tenant_status', 'leads', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leads_urgency'), 'leads', ['urgency'], unique=False)
    op.create_table('call_logs',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('call_direction', sa.Enum('INBOUND', 'OUTBOUND', name='calldirection'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentimentscore'), nullable=True),
    sa.Column('outcome', sa.Enum('CONNECTED', 'NO_ANSWER', 'VOICEMAIL', 'BUSY', 'FAILED', 'SCHEDULED_CALLBACK', name='calloutcome'), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.String(length=10), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_cost', 'call_logs', ['cost'], unique=False)
    op.create_index('idx_call_follow_up', 'call_logs', ['follow_up_required', 'created_at'], unique=False)
    op.create_index('idx_call_lead_direction', 'call_logs', ['lead_id', 'call_direction'], unique=False)
    op.create_index('idx_call_outcome_sentiment', 'call_logs', ['outcome', 'sentiment'], unique=False)
    op.create_index(op.f('ix_call_logs_call_direction'), 'call_logs', ['call_direction'], unique=False)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_lead_id'), 'call_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_call_logs_outcome'), 'call_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_call_logs_sentiment'), 'call_logs', ['sentiment'], unique=False)
    op.create_table('chatbot_sessions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('intent_detected', sa.String(length=255), nullable=True),
    sa.Column('entities_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('lead_captured', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chatbot_engagement', 'chatbot_sessions', ['engagement_score'], unique=False)
    op.create_index('idx_chatbot_lead_captured', 'chatbot_sessions', ['lead_captured'], unique=False)
    op.create_index('idx_chatbot_session_lead', 'chatbot_sessions', ['lead_id'], unique=False)
    op.create_index('idx_chatbot_session_tenant', 'chatbot_sessions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chatbot_sessions_created_at'), 'chatbot_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatbot_sessions_id'), 'chatbot_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_sessions_lead_id'), 'chatbot_sessions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_chatbot_sessions_session_id'), 'chatbot_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_chatbot_sessions_tenant_id'), 'chatbot_sessions', ['tenant_id'], unique=False)
    op.create_table('demos',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.String(length=10), nullable=True),
    sa.Column('attended', sa.String(length=10), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('ENROLLED', 'INTERESTED', 'NOT_INTERESTED', 'RESCHEDULE', 'NO_SHOW', name='demooutcome'), nullable=True),
    sa.Column('interest_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('courses_demonstrated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_scheduled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demo_completed_outcome', 'demos', ['completed', 'outcome'], unique=False)
    op.create_index('idx_demo_follow_up', 'demos', ['follow_up_scheduled'], unique=False)
    op.create_index('idx_demo_lead_scheduled', 'demos', ['lead_id', 'scheduled_at'], unique=False)
    op.create_index('idx_demo_scheduled_at', 'demos', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_demos_attended'), 'demos', ['attended'], unique=False)
    op.create_index(op.f('ix_demos_completed'), 'demos', ['completed'], unique=False)
    op.create_index(op.f('ix_demos_created_at'), 'demos', ['created_at'], unique=False)
    op.create_index(op.f('ix_demos_id'), 'demos', ['id'], unique=False)
    op.create_index(op.f('ix_demos_lead_id'), 'demos', ['lead_id'], unique=False)
    op.create_index(op.f('ix_demos_outcome'), 'demos', ['outcome'], unique=False)
    op.create_index(op.f('ix_demos_scheduled_at'), 'demos', ['scheduled_at'], unique=False)
    op.create_table('enrollments',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_plan', sa.String(length=50), nullable=True),
    sa.Column('installments_total', sa.Integer(), nullable=True),
    sa.Column('installments_paid', sa.Integer(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('enrollment_notes', sa.String(length=1000), nullable=True),
    sa.Column('special_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollment_amount', 'enrollments', ['total_amount', 'amount_paid'], unique=False)
    op.create_index('idx_enrollment_batch', 'enrollments', ['batch_id', 'enrolled_at'], unique=False)
    op.create_index('idx_enrollment_dates', 'enrollments', ['enrolled_at', 'start_date'], unique=False)
    op.create_index('idx_enrollment_lead_course', 'enrollments', ['lead_id', 'course_id'], unique=False)
    op.create_index('idx_enrollment_payment_status', 'enrollments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_enrollments_batch_id'), 'enrollments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_created_at'), 'enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrollments_enrolled_at'), 'enrollments', ['enrolled_at'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_lead_id'), 'enrollments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrollments_payment_status'), 'enrollments', ['payment_status'], unique=False)
    op.create_table('students',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lms_user_id', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('total_study_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assignments_completed', sa.Integer(), nullable=True),
    sa.Column('assignments_total', sa.Integer(), nullable=True),
    sa.Column('modules_completed', sa.Integer(), nullable=True),
    sa.Column('modules_total', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_module', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_streak', sa.Integer(), nullable=True),
    sa.Column('total_logins', sa.Integer(), nullable=True),
    sa.Column('average_assignment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quiz_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=50), nullable=True),
    sa.Column('communication_frequency', sa.String(length=50), nullable=True),
    sa.Column('mentor_assigned', sa.UUID(), nullable=True),
    sa.Column('support_tickets_count', sa.Integer(), nullable=True),
    sa.Column('mentoring_sessions_count', sa.Integer(), nullable=True),
    sa.Column('learning_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_objectives', sa.String(length=500), nullable=True),
    sa.Column('feedback_provided', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_completion', 'students', ['completion_percentage'], unique=False)
    op.create_index('idx_student_enrollment', 'students', ['enrollment_id'], unique=False)
    op.create_index('idx_student_last_active', 'students', ['last_active'], unique=False)
    op.create_index('idx_student_lms_id', 'students', ['lms_user_id'], unique=False)
    op.create_index('idx_student_risk_level', 'students', ['risk_level', 'risk_score'], unique=False)
    op.create_index('idx_student_tenant_engagement', 'students', ['tenant_id', 'engagement_score'], unique=False)
    op.create_index(op.f('ix_students_created_at'), 'students', ['created_at'], unique=False)
    op.create_index(op.f('ix_students_engagement_score'), 'students', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_students_enrollment_id'), 'students', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_last_active'), 'students', ['last_active'], unique=False)
    op.create_index(op.f('ix_students_lead_id'), 'students', ['lead_id'], unique=False)
    op.create_index(op.f('ix_students_lms_user_id'), 'students', ['lms_user_id'], unique=False)
    op.create_index(op.f('ix_students_risk_level'), 'students', ['risk_level'], unique=False)
    op.create_index(op.f('ix_students_risk_score'), 'students', ['risk_score'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_table('teaching_interactions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=True),
    sa.Column('lesson_id', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('interaction_type', sa.Enum('QUESTION', 'CLARIFICATION', 'ASSIGNMENT_HELP', 'CONCEPT_EXPLANATION', 'FEEDBACK_REQUEST', 'TECHNICAL_ISSUE', 'OTHER', name='interactiontype'), nullable=False),
    sa.Column('confusion_level', sa.Enum('CLEAR', 'SLIGHT', 'MODERATE', 'HIGH', 'VERY_HIGH', name='confusionlevel'), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concepts_discussed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('entities_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.String(length=10), nullable=True),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=True),
    sa.Column('follow_up_required', sa.String(length=10), nullable=True),
    sa.Column('helpful_rating', sa.Integer(), nullable=True),
    sa.Column('clarity_rating', sa.Integer(), nullable=True),
    sa.Column('interaction_source', sa.String(length=50), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('response_method', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teaching_confusion_level', 'teaching_interactions', ['confusion_level'], unique=False)
    op.create_index('idx_teaching_follow_up', 'teaching_interactions', ['follow_up_required'], unique=False)
    op.create_index('idx_teaching_interaction_type', 'teaching_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_teaching_module_topic', 'teaching_interactions', ['module_id', 'topic'], unique=False)
    op.create_index('idx_teaching_resolved', 'teaching_interactions', ['resolved', 'created_at'], unique=False)
    op.create_index('idx_teaching_student_course', 'teaching_interactions', ['student_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_confusion_level'), 'teaching_interactions', ['confusion_level'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_course_id'), 'teaching_interactions', ['course_id'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_created_at'), 'teaching_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_id'), 'teaching_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_interaction_type'), 'teaching_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_module_id'), 'teaching_interactions', ['module_id'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_resolved'), 'teaching_interactions', ['resolved'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_student_id'), 'teaching_interactions', ['student_id'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_topic'), 'teaching_interactions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_interactions_topic'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_student_id'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_resolved'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_module_id'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_interaction_type'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_id'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_created_at'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_course_id'), table_name='teaching_interactions')
    op.drop_index(op.f('ix_teaching_interactions_confusion_level'), table_name='teaching_interactions')
    op.drop_index('idx_teaching_student_course', table_name='teaching_interactions')
    op.drop_index('idx_teaching_resolved', table_name='teaching_interactions')
    op.drop_index('idx_teaching_module_topic', table_name='teaching_interactions')
    op.drop_index('idx_teaching_interaction_type', table_name='teaching_interactions')
    op.drop_index('idx_teaching_follow_up', table_name='teaching_interactions')
    op.drop_index('idx_teaching_confusion_level', table_name='teaching_interactions')
    op.drop_table('teaching_interactions')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_risk_score'), table_name='students')
    op.drop_index(op.f('ix_students_risk_level'), table_name='students')
    op.drop_index(op.f('ix_students_lms_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_lead_id'), table_name='students')
    op.drop_index(op.f('ix_students_last_active'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_enrollment_id'), table_name='students')
    op.drop_index(op.f('ix_students_engagement_score'), table_name='students')
    op.drop_index(op.f('ix_students_created_at'), table_name='students')
    op.drop_index('idx_student_tenant_engagement', table_name='students')
    op.drop_index('idx_student_risk_level', table_name='students')
    op.drop_index('idx_student_lms_id', table_name='students')
    op.drop_index('idx_student_last_active', table_name='students')
    op.drop_index('idx_student_enrollment', table_name='students')
    op.drop_index('idx_student_completion', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_enrollments_payment_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_lead_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrolled_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_created_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_batch_id'), table_name='enrollments')
    op.drop_index('idx_enrollment_payment_status', table_name='enrollments')
    op.drop_index('idx_enrollment_lead_course', table_name='enrollments')
    op.drop_index('idx_enrollment_dates', table_name='enrollments')
    op.drop_index('idx_enrollment_batch', table_name='enrollments')
    op.drop_index('idx_enrollment_amount', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_demos_scheduled_at'), table_name='demos')
    op.drop_index(op.f('ix_demos_outcome'), table_name='demos')
    op.drop_index(op.f('ix_demos_lead_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_created_at'), table_name='demos')
    op.drop_index(op.f('ix_demos_completed'), table_name='demos')
    op.drop_index(op.f('ix_demos_attended'), table_name='demos')
    op.drop_index('idx_demo_scheduled_at', table_name='demos')
    op.drop_index('idx_demo_lead_scheduled', table_name='demos')
    op.drop_index('idx_demo_follow_up', table_name='demos')
    op.drop_index('idx_demo_completed_outcome', table_name='demos')
    op.drop_table('demos')
    op.drop_index(op.f('ix_chatbot_sessions_tenant_id'), table_name='chatbot_sessions')
    op.drop_index(op.f('ix_chatbot_sessions_session_id'), table_name='chatbot_sessions')
    op.drop_index(op.f('ix_chatbot_sessions_lead_id'), table_name='chatbot_sessions')
    op.drop_index(op.f('ix_chatbot_sessions_id'), table_name='chatbot_sessions')
    op.drop_index(op.f('ix_chatbot_sessions_created_at'), table_name='chatbot_sessions')
    op.drop_index('idx_chatbot_session_tenant', table_name='chatbot_sessions')
    op.drop_index('idx_chatbot_session_lead', table_name='chatbot_sessions')
    op.drop_index('idx_chatbot_lead_captured', table_name='chatbot_sessions')
    op.drop_index('idx_chatbot_engagement', table_name='chatbot_sessions')
    op.drop_table('chatbot_sessions')
    op.drop_index(op.f('ix_call_logs_sentiment'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_outcome'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_lead_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_direction'), table_name='call_logs')
    op.drop_index('idx_call_outcome_sentiment', table_name='call_logs')
    op.drop_index('idx_call_lead_direction', table_name='call_logs')
    op.drop_index('idx_call_follow_up', table_name='call_logs')
    op.drop_index('idx_call_cost', table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_leads_urgency'), table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_index('idx_lead_tenant_status', table_name='leads')
    op.drop_index('idx_lead_tenant_source', table_name='leads')
    op.drop_index('idx_lead_engagement_score', table_name='leads')
    op.drop_index('idx_lead_email_phone', table_name='leads')
    op.drop_index('idx_lead_assigned_status', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_tenant_role', table_name='users')
    op.drop_index('idx_user_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_published'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_active'), table_name='courses')
    op.drop_index(op.f('ix_courses_indexed'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_index('idx_course_tenant_active', table_name='courses')
    op.drop_index('idx_course_indexed', table_name='courses')
    op.drop_index('idx_course_enrollment_count', table_name='courses')
    op.drop_index('idx_course_category_published', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_tenant_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_source'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_is_test_data'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_entity_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_entity_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index('idx_analytics_user', table_name='analytics_events')
    op.drop_index('idx_analytics_test_data', table_name='analytics_events')
    op.drop_index('idx_analytics_tenant_event_type', table_name='analytics_events')
    op.drop_index('idx_analytics_source_channel', table_name='analytics_events')
    op.drop_index('idx_analytics_session', table_name='analytics_events')
    op.drop_index('idx_analytics_revenue', table_name='analytics_events')
    op.drop_index('idx_analytics_errors', table_name='analytics_events')
    op.drop_index('idx_analytics_entity', table_name='analytics_events')
    op.drop_index('idx_analytics_created_at', table_name='analytics_events')
    op.drop_index('idx_analytics_campaign', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_tenants_subscription_plan'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index('idx_tenant_plan_credits', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
