"""add_tenant_id_to_enrollments

Revision ID: 4ebe485a33df
Revises: a1b2c3d4e5f6
Create Date: 2026-02-10 21:41:16.511974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ebe485a33df'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('call_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chatbot_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('demos', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('demos', sa.Column('mentor_id', sa.UUID(), nullable=False))
    op.add_column('demos', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('demos', sa.Column('reschedule_count', sa.Integer(), nullable=False))
    # Cast string flags to proper boolean types explicitly
    op.execute(
        "ALTER TABLE demos ALTER COLUMN completed "
        "TYPE BOOLEAN USING completed::boolean"
    )
    op.execute(
        "ALTER TABLE demos ALTER COLUMN attended "
        "TYPE BOOLEAN USING attended::boolean"
    )
    op.alter_column('demos', 'outcome',
               existing_type=postgresql.ENUM('ENROLLED', 'INTERESTED', 'NOT_INTERESTED', 'RESCHEDULE', 'NO_SHOW', name='demooutcome'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('demos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_demo_completed_outcome', table_name='demos')
    op.drop_index('idx_demo_lead_scheduled', table_name='demos')
    op.create_index('idx_demo_tenant_lead', 'demos', ['tenant_id', 'lead_id'], unique=False)
    op.create_index(op.f('ix_demos_course_id'), 'demos', ['course_id'], unique=False)
    op.create_index(op.f('ix_demos_mentor_id'), 'demos', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_demos_tenant_id'), 'demos', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'demos', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'demos', 'users', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'demos', 'tenants', ['tenant_id'], ['id'])
    op.add_column('enrollments', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('enrollments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_enrollment_tenant_lead', 'enrollments', ['tenant_id', 'lead_id'], unique=False)
    op.create_index(op.f('ix_enrollments_tenant_id'), 'enrollments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('leads', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teaching_interactions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tenants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('teaching_interactions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('students', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('leads', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_enrollments_tenant_id'), table_name='enrollments')
    op.drop_index('idx_enrollment_tenant_lead', table_name='enrollments')
    op.alter_column('enrollments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('enrollments', 'tenant_id')
    op.drop_constraint(None, 'demos', type_='foreignkey')
    op.drop_constraint(None, 'demos', type_='foreignkey')
    op.drop_constraint(None, 'demos', type_='foreignkey')
    op.drop_index(op.f('ix_demos_tenant_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_mentor_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_course_id'), table_name='demos')
    op.drop_index('idx_demo_tenant_lead', table_name='demos')
    op.create_index('idx_demo_lead_scheduled', 'demos', ['lead_id', 'scheduled_at'], unique=False)
    op.create_index('idx_demo_completed_outcome', 'demos', ['completed', 'outcome'], unique=False)
    op.alter_column('demos', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('demos', 'outcome',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ENROLLED', 'INTERESTED', 'NOT_INTERESTED', 'RESCHEDULE', 'NO_SHOW', name='demooutcome'),
               existing_nullable=True)
    op.execute(
        "ALTER TABLE demos ALTER COLUMN attended "
        "TYPE VARCHAR(10) USING attended::text"
    )
    op.execute(
        "ALTER TABLE demos ALTER COLUMN completed "
        "TYPE VARCHAR(10) USING completed::text"
    )
    op.drop_column('demos', 'reschedule_count')
    op.drop_column('demos', 'course_id')
    op.drop_column('demos', 'mentor_id')
    op.drop_column('demos', 'tenant_id')
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('chatbot_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('call_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('analytics_events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
