"""add_is_deleted_column

Revision ID: 57ffa2e0901c
Revises: 2b186ef4ecbf
Create Date: 2026-02-07 06:43:01.380868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ffa2e0901c'
down_revision = '2b186ef4ecbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first with server_default
    op.add_column('analytics_events', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('call_logs', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('chatbot_sessions', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('courses', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('demos', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('enrollments', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('leads', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('students', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('teaching_interactions', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('tenants', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    
    # Now make them NOT NULL
    op.alter_column('analytics_events', 'is_deleted', nullable=False)
    op.alter_column('call_logs', 'is_deleted', nullable=False)
    op.alter_column('chatbot_sessions', 'is_deleted', nullable=False)
    op.alter_column('courses', 'is_deleted', nullable=False)
    op.alter_column('demos', 'is_deleted', nullable=False)
    op.alter_column('enrollments', 'is_deleted', nullable=False)
    op.alter_column('leads', 'is_deleted', nullable=False)
    op.alter_column('students', 'is_deleted', nullable=False)
    op.alter_column('teaching_interactions', 'is_deleted', nullable=False)
    op.alter_column('tenants', 'is_deleted', nullable=False)
    op.alter_column('users', 'is_deleted', nullable=False)
    
    # Create indexes
    op.create_index(op.f('ix_analytics_events_is_deleted'), 'analytics_events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_call_logs_is_deleted'), 'call_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chatbot_sessions_is_deleted'), 'chatbot_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_courses_is_deleted'), 'courses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_demos_is_deleted'), 'demos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_enrollments_is_deleted'), 'enrollments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_students_is_deleted'), 'students', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teaching_interactions_is_deleted'), 'teaching_interactions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_column('tenants', 'is_deleted')
    op.drop_index(op.f('ix_teaching_interactions_is_deleted'), table_name='teaching_interactions')
    op.drop_column('teaching_interactions', 'is_deleted')
    op.drop_index(op.f('ix_students_is_deleted'), table_name='students')
    op.drop_column('students', 'is_deleted')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_column('leads', 'is_deleted')
    op.drop_index(op.f('ix_enrollments_is_deleted'), table_name='enrollments')
    op.drop_column('enrollments', 'is_deleted')
    op.drop_index(op.f('ix_demos_is_deleted'), table_name='demos')
    op.drop_column('demos', 'is_deleted')
    op.drop_index(op.f('ix_courses_is_deleted'), table_name='courses')
    op.drop_column('courses', 'is_deleted')
    op.drop_index(op.f('ix_chatbot_sessions_is_deleted'), table_name='chatbot_sessions')
    op.drop_column('chatbot_sessions', 'is_deleted')
    op.drop_index(op.f('ix_call_logs_is_deleted'), table_name='call_logs')
    op.drop_column('call_logs', 'is_deleted')
    op.drop_index(op.f('ix_analytics_events_is_deleted'), table_name='analytics_events')
    op.drop_column('analytics_events', 'is_deleted')
    # ### end Alembic commands ###